language: node_js
node_js: 6
dist: trusty
sudo: required
before_script:
- npm run test:lint
script:
- set -e
- xvfb-run wct test --skip-plugin sauce
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then xvfb-run wct test --skip-plugin local; fi'
env:
  global:
    SAUCE_USERNAME: Desire2Learn
