language: node_js
node_js: "9"
script:
- npm run test:lint
- polymer test --skip-plugin local
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  #SAUCE_ACCESS_KEY
  - secure: WGWfX75cBoMi0A8MuZa9jZLpqq+zmZbtdBm4CDxG4HrXrX8WaoM0TifM2y24ZJ8j2LzyWMmTXLweiQPcl893w4RoF4UE+aLlhS/6UUfLP9R3+L7S+7J6tLps3m4BZdPFHWTJt145ZQRL56OPSnIxLCH5cCeFGWXbwfY97tYzaoVGrr0IAtHqzIUIMK1MshWyj4Njn6oKeKnv3pejxjDYVDIckF6F5AHq3kLiVIMz3jERr7B809cpt3mhVlt0NO8AkFA+iY2c1y+1g8u/7nwQ4gCf25zfWtPNcYpLLvJShI5/Ro2H5YhC3v5p/7w5qybsHk7VGNDgYmEF9rsDKuiOdthTgApMDQ3p05HfoM5mKdsdkYahVgBFwNvzh1VVoeMMTxOVT73h1rww3Mj+WsnzeZC7cQSJxkbhODMiYSLAAsS0DjArUMKpNbanjGwPzsccyuKocbrDxkLBg3KELYFWkLTO04YSsJyKEucVOFs4pvhUBAA4d2mOMz3ZNh/oxq8NHqPMe7Av7k/AWNgC6boBqGMlnMFtaOyBx3dR76gQp5npOnWHZNoYSXjqc0YjSvFufsjnyCQvIU7PvFo428OorVZqpSgexyNLfSMSVJwNIi6LGobXFeJCWUZn6CYBUAk1Z0WbSRliPwQmJsPErTiS0UuRinz548roYK7R3qT35oY=
